export const thumbnails = [
  "/video1.png",
  "/video2.png",
  "/video3.png",
  "/video4.png",
  "/video5.png",
  "/video6.png",
  "/video7.png",
  "/video8.png",
  "/video9.png",
];
export const testimonials = ["/Test1.png", "/Test2.png", "/Test3.png"];
export const testimonials2 = [
  "/test/Gavin_RossDale.png",
  "/test/Dominic.png",
  "/test/test_1.png",
  "test/test_2.png",
  "/test/StrangeParts.png",
];
// export const teams2 = [
//   "/team/RupeshShinde_2.png",
//   "/team/JonasBritto_2.png",
//   "/team/SauravKarmakar_2.png",
//   "/team/PranavRatra_2.png",
//   "/team/AsadRazaKhan_2.png",
//   "/team/Nandan_2.png",
//   "/team/VijaySharma_2.png",
//   "/team/Rahul_2.png",
//   "/team/Newel_2.png",
//   "/team/JoshuaFreitas_2.png",
//   "/team/JustusGomes_2.png",
//   "/team/Kaushik_2.png",
//   "/team/Atma_2.png",
// ];
export const teams = [
  "/team/v2/1.png",
  "/team/v2/2.png",
  "/team/v2/3.png",
  "/team/v2/4.png",
  "/team/v2/5.png",
  "/team/v2/6.png",
  "/team/v2/7.png",
  "/team/v2/8.png",
  "/team/v2/9.png",
  "/team/v2/10.png",
  "/team/v2/11.png",
  "/team/v2/12.png",
  "/team/v2/13.png",
  "/team/v2/14.png",
  "/team/v2/15.png",
  "/team/v2/16.png",
  "/team/v2/17.png",
  "/team/v2/18.png",
  "/team/v2/19.png",
  "/team/v2/20.png",
  "/team/v2/21.png",
  "/team/v2/22.png",
  "/team/v2/23.png",
  "/team/v2/24.png",
  "/team/v2/25.png",
];
